//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Governor.Umbraco.FullTextSearch.Console.FullTextService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://umbraco.org/webservices/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://umbraco.org/webservices/", ConfigurationName="FullTextService.FullTextServiceSoap")]
    public interface FullTextServiceSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://umbraco.org/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://umbraco.org/webservices/GetWebservicesVersion", ReplyAction="*")]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.GetWebservicesVersionResponse GetWebservicesVersion(Governor.Umbraco.FullTextSearch.Console.FullTextService.GetWebservicesVersionRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://umbraco.org/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://umbraco.org/webservices/RebuildFullTextIndex", ReplyAction="*")]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.RebuildFullTextIndexResponse RebuildFullTextIndex(Governor.Umbraco.FullTextSearch.Console.FullTextService.RebuildFullTextIndexRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://umbraco.org/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://umbraco.org/webservices/ReindexFullTextNodes", ReplyAction="*")]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesResponse ReindexFullTextNodes(Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://umbraco.org/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://umbraco.org/webservices/ReindexAllFullTextNodes", ReplyAction="*")]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexAllFullTextNodesResponse ReindexAllFullTextNodes(Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexAllFullTextNodesRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://umbraco.org/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://umbraco.org/webservices/ReindexFullTextNodesAndChildren", ReplyAction="*")]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesAndChildrenResponse ReindexFullTextNodesAndChildren(Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesAndChildrenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://umbraco.org/webservices/WebservicesEnabled", ReplyAction="*")]
        bool WebservicesEnabled();
        
        // CODEGEN: Generating message contract since element name username from namespace http://umbraco.org/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://umbraco.org/webservices/UserAuthenticates", ReplyAction="*")]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.UserAuthenticatesResponse UserAuthenticates(Governor.Umbraco.FullTextSearch.Console.FullTextService.UserAuthenticatesRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://umbraco.org/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://umbraco.org/webservices/UserHasAccess", ReplyAction="*")]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.UserHasAccessResponse UserHasAccess(Governor.Umbraco.FullTextSearch.Console.FullTextService.UserHasAccessRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebservicesVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebservicesVersion", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.GetWebservicesVersionRequestBody Body;
        
        public GetWebservicesVersionRequest() {
        }
        
        public GetWebservicesVersionRequest(Governor.Umbraco.FullTextSearch.Console.FullTextService.GetWebservicesVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://umbraco.org/webservices/")]
    public partial class GetWebservicesVersionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetWebservicesVersionRequestBody() {
        }
        
        public GetWebservicesVersionRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWebservicesVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWebservicesVersionResponse", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.GetWebservicesVersionResponseBody Body;
        
        public GetWebservicesVersionResponse() {
        }
        
        public GetWebservicesVersionResponse(Governor.Umbraco.FullTextSearch.Console.FullTextService.GetWebservicesVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://umbraco.org/webservices/")]
    public partial class GetWebservicesVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWebservicesVersionResult;
        
        public GetWebservicesVersionResponseBody() {
        }
        
        public GetWebservicesVersionResponseBody(string GetWebservicesVersionResult) {
            this.GetWebservicesVersionResult = GetWebservicesVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RebuildFullTextIndexRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RebuildFullTextIndex", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.RebuildFullTextIndexRequestBody Body;
        
        public RebuildFullTextIndexRequest() {
        }
        
        public RebuildFullTextIndexRequest(Governor.Umbraco.FullTextSearch.Console.FullTextService.RebuildFullTextIndexRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://umbraco.org/webservices/")]
    public partial class RebuildFullTextIndexRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public RebuildFullTextIndexRequestBody() {
        }
        
        public RebuildFullTextIndexRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RebuildFullTextIndexResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RebuildFullTextIndexResponse", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.RebuildFullTextIndexResponseBody Body;
        
        public RebuildFullTextIndexResponse() {
        }
        
        public RebuildFullTextIndexResponse(Governor.Umbraco.FullTextSearch.Console.FullTextService.RebuildFullTextIndexResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RebuildFullTextIndexResponseBody {
        
        public RebuildFullTextIndexResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReindexFullTextNodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReindexFullTextNodes", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesRequestBody Body;
        
        public ReindexFullTextNodesRequest() {
        }
        
        public ReindexFullTextNodesRequest(Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://umbraco.org/webservices/")]
    public partial class ReindexFullTextNodesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.ArrayOfInt nodes;
        
        public ReindexFullTextNodesRequestBody() {
        }
        
        public ReindexFullTextNodesRequestBody(string username, string password, Governor.Umbraco.FullTextSearch.Console.FullTextService.ArrayOfInt nodes) {
            this.username = username;
            this.password = password;
            this.nodes = nodes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReindexFullTextNodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReindexFullTextNodesResponse", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesResponseBody Body;
        
        public ReindexFullTextNodesResponse() {
        }
        
        public ReindexFullTextNodesResponse(Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReindexFullTextNodesResponseBody {
        
        public ReindexFullTextNodesResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReindexAllFullTextNodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReindexAllFullTextNodes", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexAllFullTextNodesRequestBody Body;
        
        public ReindexAllFullTextNodesRequest() {
        }
        
        public ReindexAllFullTextNodesRequest(Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexAllFullTextNodesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://umbraco.org/webservices/")]
    public partial class ReindexAllFullTextNodesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public ReindexAllFullTextNodesRequestBody() {
        }
        
        public ReindexAllFullTextNodesRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReindexAllFullTextNodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReindexAllFullTextNodesResponse", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexAllFullTextNodesResponseBody Body;
        
        public ReindexAllFullTextNodesResponse() {
        }
        
        public ReindexAllFullTextNodesResponse(Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexAllFullTextNodesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReindexAllFullTextNodesResponseBody {
        
        public ReindexAllFullTextNodesResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReindexFullTextNodesAndChildrenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReindexFullTextNodesAndChildren", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesAndChildrenRequestBody Body;
        
        public ReindexFullTextNodesAndChildrenRequest() {
        }
        
        public ReindexFullTextNodesAndChildrenRequest(Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesAndChildrenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://umbraco.org/webservices/")]
    public partial class ReindexFullTextNodesAndChildrenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.ArrayOfInt nodes;
        
        public ReindexFullTextNodesAndChildrenRequestBody() {
        }
        
        public ReindexFullTextNodesAndChildrenRequestBody(string username, string password, Governor.Umbraco.FullTextSearch.Console.FullTextService.ArrayOfInt nodes) {
            this.username = username;
            this.password = password;
            this.nodes = nodes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReindexFullTextNodesAndChildrenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReindexFullTextNodesAndChildrenResponse", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesAndChildrenResponseBody Body;
        
        public ReindexFullTextNodesAndChildrenResponse() {
        }
        
        public ReindexFullTextNodesAndChildrenResponse(Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesAndChildrenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ReindexFullTextNodesAndChildrenResponseBody {
        
        public ReindexFullTextNodesAndChildrenResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserAuthenticatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserAuthenticates", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.UserAuthenticatesRequestBody Body;
        
        public UserAuthenticatesRequest() {
        }
        
        public UserAuthenticatesRequest(Governor.Umbraco.FullTextSearch.Console.FullTextService.UserAuthenticatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://umbraco.org/webservices/")]
    public partial class UserAuthenticatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public UserAuthenticatesRequestBody() {
        }
        
        public UserAuthenticatesRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserAuthenticatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserAuthenticatesResponse", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.UserAuthenticatesResponseBody Body;
        
        public UserAuthenticatesResponse() {
        }
        
        public UserAuthenticatesResponse(Governor.Umbraco.FullTextSearch.Console.FullTextService.UserAuthenticatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://umbraco.org/webservices/")]
    public partial class UserAuthenticatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UserAuthenticatesResult;
        
        public UserAuthenticatesResponseBody() {
        }
        
        public UserAuthenticatesResponseBody(bool UserAuthenticatesResult) {
            this.UserAuthenticatesResult = UserAuthenticatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasAccessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasAccess", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.UserHasAccessRequestBody Body;
        
        public UserHasAccessRequest() {
        }
        
        public UserHasAccessRequest(Governor.Umbraco.FullTextSearch.Console.FullTextService.UserHasAccessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://umbraco.org/webservices/")]
    public partial class UserHasAccessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public UserHasAccessRequestBody() {
        }
        
        public UserHasAccessRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UserHasAccessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UserHasAccessResponse", Namespace="http://umbraco.org/webservices/", Order=0)]
        public Governor.Umbraco.FullTextSearch.Console.FullTextService.UserHasAccessResponseBody Body;
        
        public UserHasAccessResponse() {
        }
        
        public UserHasAccessResponse(Governor.Umbraco.FullTextSearch.Console.FullTextService.UserHasAccessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://umbraco.org/webservices/")]
    public partial class UserHasAccessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UserHasAccessResult;
        
        public UserHasAccessResponseBody() {
        }
        
        public UserHasAccessResponseBody(bool UserHasAccessResult) {
            this.UserHasAccessResult = UserHasAccessResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FullTextServiceSoapChannel : Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FullTextServiceSoapClient : System.ServiceModel.ClientBase<Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap>, Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap {
        
        public FullTextServiceSoapClient() {
        }
        
        public FullTextServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FullTextServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FullTextServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FullTextServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.GetWebservicesVersionResponse Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap.GetWebservicesVersion(Governor.Umbraco.FullTextSearch.Console.FullTextService.GetWebservicesVersionRequest request) {
            return base.Channel.GetWebservicesVersion(request);
        }
        
        public string GetWebservicesVersion(string username, string password) {
            Governor.Umbraco.FullTextSearch.Console.FullTextService.GetWebservicesVersionRequest inValue = new Governor.Umbraco.FullTextSearch.Console.FullTextService.GetWebservicesVersionRequest();
            inValue.Body = new Governor.Umbraco.FullTextSearch.Console.FullTextService.GetWebservicesVersionRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Governor.Umbraco.FullTextSearch.Console.FullTextService.GetWebservicesVersionResponse retVal = ((Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap)(this)).GetWebservicesVersion(inValue);
            return retVal.Body.GetWebservicesVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.RebuildFullTextIndexResponse Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap.RebuildFullTextIndex(Governor.Umbraco.FullTextSearch.Console.FullTextService.RebuildFullTextIndexRequest request) {
            return base.Channel.RebuildFullTextIndex(request);
        }
        
        public void RebuildFullTextIndex(string username, string password) {
            Governor.Umbraco.FullTextSearch.Console.FullTextService.RebuildFullTextIndexRequest inValue = new Governor.Umbraco.FullTextSearch.Console.FullTextService.RebuildFullTextIndexRequest();
            inValue.Body = new Governor.Umbraco.FullTextSearch.Console.FullTextService.RebuildFullTextIndexRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Governor.Umbraco.FullTextSearch.Console.FullTextService.RebuildFullTextIndexResponse retVal = ((Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap)(this)).RebuildFullTextIndex(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesResponse Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap.ReindexFullTextNodes(Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesRequest request) {
            return base.Channel.ReindexFullTextNodes(request);
        }
        
        public void ReindexFullTextNodes(string username, string password, Governor.Umbraco.FullTextSearch.Console.FullTextService.ArrayOfInt nodes) {
            Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesRequest inValue = new Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesRequest();
            inValue.Body = new Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.nodes = nodes;
            Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesResponse retVal = ((Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap)(this)).ReindexFullTextNodes(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexAllFullTextNodesResponse Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap.ReindexAllFullTextNodes(Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexAllFullTextNodesRequest request) {
            return base.Channel.ReindexAllFullTextNodes(request);
        }
        
        public void ReindexAllFullTextNodes(string username, string password) {
            Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexAllFullTextNodesRequest inValue = new Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexAllFullTextNodesRequest();
            inValue.Body = new Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexAllFullTextNodesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexAllFullTextNodesResponse retVal = ((Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap)(this)).ReindexAllFullTextNodes(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesAndChildrenResponse Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap.ReindexFullTextNodesAndChildren(Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesAndChildrenRequest request) {
            return base.Channel.ReindexFullTextNodesAndChildren(request);
        }
        
        public void ReindexFullTextNodesAndChildren(string username, string password, Governor.Umbraco.FullTextSearch.Console.FullTextService.ArrayOfInt nodes) {
            Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesAndChildrenRequest inValue = new Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesAndChildrenRequest();
            inValue.Body = new Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesAndChildrenRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.nodes = nodes;
            Governor.Umbraco.FullTextSearch.Console.FullTextService.ReindexFullTextNodesAndChildrenResponse retVal = ((Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap)(this)).ReindexFullTextNodesAndChildren(inValue);
        }
        
        public bool WebservicesEnabled() {
            return base.Channel.WebservicesEnabled();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.UserAuthenticatesResponse Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap.UserAuthenticates(Governor.Umbraco.FullTextSearch.Console.FullTextService.UserAuthenticatesRequest request) {
            return base.Channel.UserAuthenticates(request);
        }
        
        public bool UserAuthenticates(string username, string password) {
            Governor.Umbraco.FullTextSearch.Console.FullTextService.UserAuthenticatesRequest inValue = new Governor.Umbraco.FullTextSearch.Console.FullTextService.UserAuthenticatesRequest();
            inValue.Body = new Governor.Umbraco.FullTextSearch.Console.FullTextService.UserAuthenticatesRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Governor.Umbraco.FullTextSearch.Console.FullTextService.UserAuthenticatesResponse retVal = ((Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap)(this)).UserAuthenticates(inValue);
            return retVal.Body.UserAuthenticatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Governor.Umbraco.FullTextSearch.Console.FullTextService.UserHasAccessResponse Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap.UserHasAccess(Governor.Umbraco.FullTextSearch.Console.FullTextService.UserHasAccessRequest request) {
            return base.Channel.UserHasAccess(request);
        }
        
        public bool UserHasAccess(string username) {
            Governor.Umbraco.FullTextSearch.Console.FullTextService.UserHasAccessRequest inValue = new Governor.Umbraco.FullTextSearch.Console.FullTextService.UserHasAccessRequest();
            inValue.Body = new Governor.Umbraco.FullTextSearch.Console.FullTextService.UserHasAccessRequestBody();
            inValue.Body.username = username;
            Governor.Umbraco.FullTextSearch.Console.FullTextService.UserHasAccessResponse retVal = ((Governor.Umbraco.FullTextSearch.Console.FullTextService.FullTextServiceSoap)(this)).UserHasAccess(inValue);
            return retVal.Body.UserHasAccessResult;
        }
    }
}
